# Generated by Django 5.0.2 on 2024-06-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.CharField(max_length=20),
        ),
    ]
