# Generated by Django 5.0.2 on 2024-06-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_taskcategory_tasks'),
        ('task', '0002_alter_taskmodel_taskassigndate'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task',
            field=models.ManyToManyField(to='category.taskcategory'),
        ),
    ]
