# Generated by Django 5.0.2 on 2024-06-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='tasks',
            field=models.ManyToManyField(related_name='categories', to='task.taskmodel'),
        ),
    ]
