# Generated by Django 5.0.2 on 2024-06-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_taskcategory_tasks'),
        ('task', '0002_alter_taskmodel_taskassigndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='tasks',
            field=models.ManyToManyField(to='task.taskmodel'),
        ),
    ]
