# Generated by Django 5.0.2 on 2024-06-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_taskcategory_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategory',
            name='tasks',
        ),
    ]
